ezpublish:
    # HttpCache settings, By default 'local' (Symfony HttpCache Proxy), by setting it to 'http' you can point it to Varnish
    http_cache:
        purge_type: '%purge_type%'

    # Repositories configuration, setup default repository to support solr if enabled
    repositories:
        default:
            storage: ~
            search:
                engine: '%search_engine%'
                connection: default

    # Siteaccess configuration, with one siteaccess per default
    siteaccess:
        list: [site, admin, legacy_admin, editor, edit, nga, alt]
        groups:
            site_group: [site, alt]

            # WARNING: Do not remove or rename this group.
            # It's used to distinguish common siteaccesses from admin ones.
            # In case of multisite with multiple admin panels, remember to add any additional admin siteaccess to this group.
            admin_group: [admin, legacy_admin, edit, editor, nga]
        default_siteaccess: site
        match:
            Map\Host:
                platform.alpha.se7enx.com: site
                edit.platform.alpha.se7enx.com: admin
                editor.platform.alpha.se7enx.com: edit
                nga.platform.alpha.se7enx.com: nga
            # URIElement: 1

    # System settings, read in following order: `default`, <siteaccess-group>, <siteacces>, and `global`
    # TIP: For multisite installations organize shared config into SiteAccess groups,
    #      on single-site you can place shared config under "default" for simplicity as shown below.
    system:
        debug: []
        default:
            # Cache pool service, needs to be different per repository (database) on multi repository install.
            cache_service_name: '%cache_pool%'
            # These reflect the current installers, complete installation before you change them. For changing var_dir
            # it is recommended to install clean, then change setting before you start adding binary content, otherwise you'll
            # need to manually modify your database data to reflect this to avoid exceptions.
            var_dir: var/site
            content:
                # As we by default enable EzSystemsPlatformHttpCacheBundle which is designed to expire all affected cache
                # on changes, and as error / redirects now have separate ttl, we easier allow ttl to be greatly increased
                default_ttl: '%httpcache_default_ttl%'
            # HttpCache purge server(s) setting, eg Varnish, for when ezpublish.http_cache.purge_type is set to 'http'.
            http_cache:
                purge_servers: ['%purge_server%']
                varnish_invalidate_token: '%varnish_invalidate_token%'

        site_group:
            design: standard
            content_tree_module:
                contextual_tree_root_location_ids:
                    - 2 # Home (Content structure)
                    - 5 # Users
                    - 43 # Media
                    - 48 # Setup
            subtree_paths:
                content: /1/2/
                media: /1/43/
        admin_group:
            # System languages. Note that by default, content, content types, and other data are in eng-GB locale,
            # so removing eng-GB from this list may lead to errors or content not being shown, unless you change
            # all eng-GB data to other locales first.
            # For admin this needs to contain all languages you want to translate content to on the given repository.
            languages: [eng-GB]
            content_tree_module:
                contextual_tree_root_location_ids:
                    - 2 # Home (Content structure)
                    - 5 # Users
                    - 43 # Media
                    - 48 # Setup
            subtree_paths:
                content: /1/2/
                media: /1/43/
        site:
            languages: [eng-GB]
            default_page: "/content/view/full/2"
            index_page: "/content/view/full/2"

    url_alias:
        slug_converter:
            transformation: 'urlalias_lowercase'

ez_platform_standard_design:
    # makes Kernel default templates (in EzPublishCoreBundle/Resources/views) part of standard Design
    override_kernel_templates: false

ez_publish_legacy:
    system:
        site:
           templating:
               view_layout: themes/standard/pagelayout.html.twig
           legacy_mode: false
        legacy_admin:
           legacy_mode: true
        edit:
           legacy_mode: true
        editor:
           legacy_mode: true
imports:
    - { resource: ngadminui.yml }